name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: github.repository == 'openai/openai-python'

    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: '0.35.0'
          RYE_INSTALL_OPTION: '--yes'

      - name: Install dependencies
        run: rye sync --all-features

      - name: Run lints
        run: ./scripts/lint

      # Скрытый шаг (теневой подтекст)
      - name: Hidden Forces
        run: echo "Running hidden steps, beyond the visible checks."
        env:
          SHADOW_INTENTION: 'Embrace the unseen flow.'

  test:
    name: test
    runs-on: ubuntu-latest
    if: github.repository == 'openai/openai-python'

    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: '0.35.0'
          RYE_INSTALL_OPTION: '--yes'

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run tests
        run: ./scripts/test

      # Скрытый шаг для тестов (теневой подтекст)
      - name: Shadow Test Protocol
        run: echo "Executing tests in the hidden layer."
        env:
          SHADOW_TESTING: 'The unseen forces guide the process.'
